### ISSUE TITLE
dfvfs unit test fails with libfvde experimental-20180108

### ISSUE THREAD

**Issue by ant1** [libyal/libfvde#33]
Hi,

With version experimental-20180108,  1 regression test from dfvfs fails:

```
======================================================================
ERROR: testScanFVDE (helpers.source_scanner.SourceScannerTest)
Test the Scan function on FVDE.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/wrkdirs/dfvfs-20171230/tests/helpers/source_scanner.py", line 182, in testScanFVDE
    self._source_scanner.Scan(scan_context)
  File "./dfvfs/helpers/source_scanner.py", line 565, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "./dfvfs/helpers/source_scanner.py", line 440, in _ScanNode
    scan_context, sub_scan_node, auto_recurse=auto_recurse)
  File "./dfvfs/helpers/source_scanner.py", line 450, in _ScanNode
    file_object.close()
  File "./dfvfs/file_io/file_io.py", line 98, in close
    self._Close()
  File "./dfvfs/file_io/file_object_io.py", line 35, in _Close
    self._file_object.close()
IOError: pyfvde_volume_close: unable to close volume. libfvde_volume_close: invalid volume - missing file IO handle.

----------------------------------------------------------------------

```

**Comment by joachimmetz** [comment]
This looks more than a dormant bug in dfvfs than regression in libfvde. Since the pyfvde volume seems to be closed multiple times.
